### ISSUE TITLE
Illegal import declaration

### ISSUE THREAD

**Issue by mattdell** [danvk/mocha-react#13]
I'm trying to follow your example here, but I'm using ES6 import declarations instead of ES5 require statements.

It seems compiler.js isn't happy about the transform, even with harmony mode enabled. Do you have any suggestions on how to get this to work with import statements?

```
Error: Parse Error: Line 10: Illegal import declaration
    at throwError (/web/node_modules/react-tools/node_modules/esprima-fb/esprima.js:2813:21)
    at throwErrorTolerant (/web/node_modules/react-tools/node_modules/esprima-fb/esprima.js:2825:24)
    at parseSourceElement (/web/node_modules/react-tools/node_modules/esprima-fb/esprima.js:6390:17)
    at parseProgramElement (/web/node_modules/react-tools/node_modules/esprima-fb/esprima.js:6446:16)
    at parseProgramElements (/web/node_modules/react-tools/node_modules/esprima-fb/esprima.js:6478:29)
    at parseProgram (/web/node_modules/react-tools/node_modules/esprima-fb/esprima.js:6491:16)
    at Object.parse (/web/node_modules/react-tools/node_modules/esprima-fb/esprima.js:7653:23)
    at getAstForSource (/web/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:251:21)
    at transform (/web/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:274:11)
    at innerTransform (/web/node_modules/react-tools/main.js:94:10)
    at Object.module.exports.transform (/web/node_modules/react-tools/main.js:20:18)
    at Object.require.extensions..js (/web/tests/compiler.js:12:30)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /web/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/web/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/web/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/web/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3`
```

**Comment by Luke1298** [comment]
+1
