### ISSUE TITLE
Coverage broken

### ISSUE THREAD

**Issue by danvk** [danvk/mocha-react#4]
It's something to do with coveralls — I can run this in my own version of the repo:

```
$ NODE_ENV=test ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter tests/*test.js
SF:/Users/danvk/github/mocha-react/src/BigComplicatedComponent.js
DA:3,2
DA:5,2
DA:7,0
DA:8,0
DA:12,2
end_of_record
SF:/Users/danvk/github/mocha-react/src/CheckboxWithLabel.js
DA:1,2
DA:2,2
DA:4,2
DA:6,1
DA:9,1
DA:12,2
DA:26,2
end_of_record
```

but when I clone a fresh repo, run `npm install` in it and run the same command, I get the same error as [on Travis](https://travis-ci.org/danvk/mocha-react#L87):

```
NODE_ENV=test ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter tests/*test.js

/private/tmp/mocha-react/tests/CheckboxWithLabel-test.js:19
      <CheckboxWithLabel labelOn="On" labelOff="Off" />
      ^
SyntaxError: Unexpected token <
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /private/tmp/mocha-react/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/private/tmp/mocha-react/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/private/tmp/mocha-react/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/private/tmp/mocha-react/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Maybe some NPM package introduced a breaking change into a "compatible" release?

**Comment by danvk** [comment]
Mocha is the culprit: coverage generation works with `mocha@2.0.1`, but fails with `mocha@2.2.1`.

**Comment by danvk** [comment]
See mochajs/mocha#1585

**Comment by danvk** [comment]
This is fixed for now by pinning an old version of Mocha. We'll have to wait until they resolve the issue upstream. Yuck.

**Comment by jxm262** [comment]
:grimacing:

**Comment by danvk** [comment]
This should be fixed once the next release of Mocha comes out.

**Comment by LongLiveCHIEF** [comment]
I don't think mocha, or coverage generation, is the culprit here either. I can reproduce this without using any coverage generation at all, and downgrading to mocha `2.0.1 or `2.1.x` still causes the error.
